package com.magikit

import androidx.annotation.DrawableRes
import com.magikit.R

enum class Card(val code: String, @DrawableRes val drawableRes: Int) {
    CA("AC", R.drawable.ca),
    C2("2C", R.drawable.c2),
    C3("3C", R.drawable.c3),
    C4("4C", R.drawable.c4),
    C5("5C", R.drawable.c5),
    C6("6C", R.drawable.c6),
    C7("7C", R.drawable.c7),
    C8("8C", R.drawable.c8),
    C9("9C", R.drawable.c9),
    C10("10C", R.drawable.c10),
    CJ("JC", R.drawable.cj),
    CQ("QC", R.drawable.cq),
    CK("KC", R.drawable.ck),
    HA("AH", R.drawable.ha),
    H2("2H", R.drawable.h2),
    H3("3H", R.drawable.h3),
    H4("4H", R.drawable.h4),
    H5("5H", R.drawable.h5),
    H6("6H", R.drawable.h6),
    H7("7H", R.drawable.h7),
    H8("8H", R.drawable.h8),
    H9("9H", R.drawable.h9),
    H10("10H", R.drawable.h10),
    HJ("JH", R.drawable.hj),
    HQ("QH", R.drawable.hq),
    HK("KH", R.drawable.hk),
    SA("AS", R.drawable.sa),
    S2("2S", R.drawable.s2),
    S3("3S", R.drawable.s3),
    S4("4S", R.drawable.s4),
    S5("5S", R.drawable.s5),
    S6("6S", R.drawable.s6),
    S7("7S", R.drawable.s7),
    S8("8S", R.drawable.s8),
    S9("9S", R.drawable.s9),
    S10("10S", R.drawable.s10),
    SJ("JS", R.drawable.sj),
    SQ("QS", R.drawable.sq),
    SK("KS", R.drawable.sk),
    DA("AD", R.drawable.da),
    D2("2D", R.drawable.d2),
    D3("3D", R.drawable.d3),
    D4("4D", R.drawable.d4),
    D5("5D", R.drawable.d5),
    D6("6D", R.drawable.d6),
    D7("7D", R.drawable.d7),
    D8("8D", R.drawable.d8),
    D9("9D", R.drawable.d9),
    D10("10D", R.drawable.d10),
    DJ("JD", R.drawable.dj),
    DQ("QD", R.drawable.dq),
    DK("KD", R.drawable.dk);
}

data class DraggableCard(val id: Int, val card: Card)
